import { Providers } from "@/app/providers"
import { ResponsiveAppBar } from "@/components/app-bar"
import type { Metadata } from "next"
import { Roboto } from "next/font/google"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="de">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className={roboto.variable}>
        <Providers>
          <ResponsiveAppBar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
